- workload=resnet50_h100
- ++workload.workflow.generate_data=True
- ++workload.workflow.train=False
- ++workload.dataset.num_files_train=50839
- ++workload.dataset.data_folder=/mnt/yrfs/mlperf/three_clients/resnet50
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
