- workload=cosmoflow_h100
- ++workload.workflow.generate_data=True
- ++workload.workflow.train=False
- ++workload.dataset.num_files_train=1429258
- ++workload.dataset.data_folder=/mnt/yrfs/mlperf/three_clients/cosmoflow/
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
