- workload=unet3d_a100
- ++workload.workflow.generate_data=True
- ++workload.workflow.train=False
- ++workload.dataset.num_files_train=84000
- ++workload.dataset.data_folder=/mnt/mlperf_storage/unet3d_data
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
