- workload=unet3d_h100
- ++workload.workflow.generate_data=True
- ++workload.workflow.train=False
- ++workload.dataset.num_files_train=14000
- ++workload.dataset.data_folder=unet3d_data_14000
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
