workload:
  model: resnet50
  framework: tensorflow
  workflow:
    generate_data: true
    train: false
    profiling: false
  dataset:
    num_files_train: 38326
    num_samples_per_file: 1251
    record_length: 114660.07
    record_length_resize: 150528
    data_folder: /6500-B7C4/resnet50
    format: tfrecord
  train:
    computation_time: 0.435
    epochs: 5
  reader:
    data_loader: tensorflow
    read_threads: 8
    computation_threads: 8
    batch_size: 400
    dont_use_mmap: true
  metric:
    au: 0.9
  profiling:
    profiler: none
