- workload=resnet50_a100
- ++workload.workflow.generate_data=True
- ++workload.workflow.train=False
- ++workload.dataset.num_files_train=38326
- ++workload.dataset.data_folder=/6500-B7C4/resnet50
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
