- workload=cosmoflow_a100
- ++workload.workflow.generate_data=True
- ++workload.workflow.train=False
- ++workload.dataset.num_files_train=476419
- ++workload.dataset.data_folder=/mnt/yrfs/mlperf/one_client/cosmoflow
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
