workload:
  model: cosmoflow
  framework: tensorflow
  workflow:
    generate_data: true
    train: false
    profiling: false
  dataset:
    data_folder: /home/light/cosmoflow-data
    num_files_train: 3000000
    num_samples_per_file: 1
    record_length: 2828486
    record_length_stdev: 71311
    format: tfrecord
  reader:
    data_loader: tensorflow
    read_threads: 4
    batch_size: 1
    file_shuffle: seed
    sample_shuffle: seed
    shuffle_size: 2
  train:
    epochs: 5
    computation_time: 0.0035
  metric:
    au: 0.7
  profiling:
    profiler: none
