- workload=cosmoflow_h100
- ++workload.workflow.generate_data=True
- ++workload.workflow.train=False
- ++workload.dataset.num_files_train=3000000
- ++workload.dataset.data_folder=/home/light/cosmoflow-data
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
