workload:
  model: resnet50
  framework: tensorflow
  workflow:
    generate_data: true
    train: false
    profiling: false
  dataset:
    num_files_train: 117375
    num_samples_per_file: 1251
    record_length: 114660.07
    record_length_resize: 150528
    data_folder: /lustre/mlperf/client/datagen_resnet50_h100
    format: tfrecord
  train:
    computation_time: 0.224
    epochs: 5
  reader:
    data_loader: tensorflow
    read_threads: 8
    computation_threads: 8
    batch_size: 400
  metric:
    au: 0.9
  storage:
    storage_type: local_fs
    storage_root: /lustre/mlperf/client
  profiling:
    profiler: none
