- workload=cosmoflow_h100
- ++workload.workflow.generate_data=True
- ++workload.workflow.train=False
- ++workload.dataset.num_files_train=61000
- ++workload.dataset.data_folder=cosmoflow_data_61000
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
