- workload=resnet50_a100
- ++workload.workflow.generate_data=True
- ++workload.workflow.train=False
- ++workload.dataset.num_files_train=30695
- ++workload.dataset.data_folder=/mnt/mlperf_storage/resnet50_data
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
