- workload=cosmoflow_a100
- ++workload.workflow.generate_data=True
- ++workload.workflow.train=False
- ++workload.dataset.num_files_train=485909
- ++workload.dataset.data_folder=/9400nvme/cosmoflow
- ++workload.dataset.num_subfolders_train=1000
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
